
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * sales_service2.java
 *
 * Created on Nov 19, 2013, 8:30:01 PM
 */
/**
 *
 * @author B.KUMAR
 */
public class sales_service2 extends javax.swing.JFrame {

    /** Creates new form sales_service2 */
    public sales_service2() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SERVICE BILLING");

        jLabel2.setText("INVOICE DATE:");

        jLabel3.setText("SERVICE TICKET ID:");

        jLabel7.setText("INVOICE ID:");

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        jTextField3.setText("jTextField3");

        jButton1.setText("print bill");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(98, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(59, 59, 59))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74))
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jButton1)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jButton1)
                .addGap(29, 29, 29)
                .addComponent(jLabel5)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String a,b,c;
        a=jTextField1.getText();
        b=jTextField2.getText();
        c=jTextField3.getText();
        
          Connection con;
	        Statement st ; 
                ResultSet rs ;
         
         
         
		try{
		
		Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
		 
		con = DriverManager.getConnection("jdbc:odbc:MS Access Database");
		st = con.createStatement();
                int d=Integer.parseInt(c);
                /*rs=st.executeQuery("SELECT SERVICE_NO FROM SERVICE_TICKET WHERE SERVICE_TICKET_ID=1");
                System.out.println(rs.getInt("SERVICE_NO"));
                pt.setInt(1,d); */
                PreparedStatement pt=con.prepareStatement("SELECT SERVICE_NO FROM SERVICE_TICKET WHERE SERVICE_TICKET_ID=?");
                pt.setInt(1,d); 
                rs=pt.executeQuery();
                int q=0;
                while(rs.next())
                {
                 q=rs.getInt("SERVICE_NO");
                }
                System.out.println(q);
		PreparedStatement pt1=con.prepareStatement("SELECT SER_CHARGE,SER_TYPE FROM SERVICE WHERE SERVICE_ID=?");
                pt1.setInt(1,q); 
                rs=pt1.executeQuery();
                int w=0;
                String s = null;
                while(rs.next())
                {
                 w=rs.getInt("SER_CHARGE");
                 s=rs.getString("SER_TYPE");
                }
                System.out.println(w);
                System.out.println(s);
                String h=String.valueOf(a);
                String hi=String.valueOf(b);
                String bye=String.valueOf(c);
                String his=String.valueOf(q);
                String her=String.valueOf(w);
                JOptionPane.showMessageDialog(this,"Invoice_id="+a+"\nInvoice Date="+b+"\nService Name="+s+"\nTotal Amount"+w);
                PreparedStatement pt3=con.prepareStatement("insert into SER_SALES values(?,?,?,?,?,?)");
		pt3.setString(1,h);
                pt3.setString(2,hi);
                pt3.setString(3,bye);
                pt3.setString(4,his);
                pt3.setString(5,null);
                pt3.setString(6,her);
                pt3.executeUpdate();
                
                /*PreparedStatement pt=con.prepareStatement("insert into SERVICE_TICKET values(?,?,?,?,?,?,?,?)");
               
		pt.setString(1,t);
                pt.setString(2,s);
                pt.setString(3,vp);
                pt.setString(4,vn);
                pt.setString(5,bd);
                pt.setString(6,dd);
                pt.setString(7,id);
                pt.setString(8,ep);
                pt.executeUpdate();
               */
                
                //rs=st.executeQuery("DELETE FROM VECHILE WHERE CHASIS_NO='"+ch+"';");
               
                 
                
                /*PreparedStatement pt1=con.prepareStatement("insert into CUSTOMERS_ADDR values(?,?,?,?,?)");
                
               
                pt1.setString(1,id);
                pt1.setString(2,ad1);
                pt1.setString(3,ad2);
                pt1.setString(4,city);
                pt1.setString(5,sta);
                pt1.setString(5,pin);
                pt1.executeUpdate();*/
                //int p=63;
                //String y= String.valueOf(p);
                //PreparedStatement p1t=con.prepareStatement("UPDATE  REGISTER SET   LAST_NAME = y' WHERE FIRST_NAME='ha';");
                // p1t.executeUpdate();
                }
		catch(ClassNotFoundException ce  )
		{
		System.out.println(ce.toString());
		}
                 catch(SQLException ee)
                 {
		System.out.println(ee.toString());
		}
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new sales_service2().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
